name: Dev

on: 
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show environment
      run: cargo --version
    - name: Run checks
      run: cargo fmt -- --check
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
